/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CommandCreated extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4464136329030560518L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CommandCreated\",\"namespace\":\"com.example.avro\",\"fields\":[{\"name\":\"commandId\",\"type\":\"long\"},{\"name\":\"products\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Product\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"long\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CommandCreated> ENCODER =
      new BinaryMessageEncoder<CommandCreated>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CommandCreated> DECODER =
      new BinaryMessageDecoder<CommandCreated>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CommandCreated> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CommandCreated> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CommandCreated> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CommandCreated>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CommandCreated to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CommandCreated from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CommandCreated instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CommandCreated fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long commandId;
  private java.util.List<com.example.avro.Product> products;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CommandCreated() {}

  /**
   * All-args constructor.
   * @param commandId The new value for commandId
   * @param products The new value for products
   */
  public CommandCreated(java.lang.Long commandId, java.util.List<com.example.avro.Product> products) {
    this.commandId = commandId;
    this.products = products;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return commandId;
    case 1: return products;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: commandId = (java.lang.Long)value$; break;
    case 1: products = (java.util.List<com.example.avro.Product>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'commandId' field.
   * @return The value of the 'commandId' field.
   */
  public long getCommandId() {
    return commandId;
  }


  /**
   * Sets the value of the 'commandId' field.
   * @param value the value to set.
   */
  public void setCommandId(long value) {
    this.commandId = value;
  }

  /**
   * Gets the value of the 'products' field.
   * @return The value of the 'products' field.
   */
  public java.util.List<com.example.avro.Product> getProducts() {
    return products;
  }


  /**
   * Sets the value of the 'products' field.
   * @param value the value to set.
   */
  public void setProducts(java.util.List<com.example.avro.Product> value) {
    this.products = value;
  }

  /**
   * Creates a new CommandCreated RecordBuilder.
   * @return A new CommandCreated RecordBuilder
   */
  public static com.example.avro.CommandCreated.Builder newBuilder() {
    return new com.example.avro.CommandCreated.Builder();
  }

  /**
   * Creates a new CommandCreated RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CommandCreated RecordBuilder
   */
  public static com.example.avro.CommandCreated.Builder newBuilder(com.example.avro.CommandCreated.Builder other) {
    if (other == null) {
      return new com.example.avro.CommandCreated.Builder();
    } else {
      return new com.example.avro.CommandCreated.Builder(other);
    }
  }

  /**
   * Creates a new CommandCreated RecordBuilder by copying an existing CommandCreated instance.
   * @param other The existing instance to copy.
   * @return A new CommandCreated RecordBuilder
   */
  public static com.example.avro.CommandCreated.Builder newBuilder(com.example.avro.CommandCreated other) {
    if (other == null) {
      return new com.example.avro.CommandCreated.Builder();
    } else {
      return new com.example.avro.CommandCreated.Builder(other);
    }
  }

  /**
   * RecordBuilder for CommandCreated instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CommandCreated>
    implements org.apache.avro.data.RecordBuilder<CommandCreated> {

    private long commandId;
    private java.util.List<com.example.avro.Product> products;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.avro.CommandCreated.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.commandId)) {
        this.commandId = data().deepCopy(fields()[0].schema(), other.commandId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.products)) {
        this.products = data().deepCopy(fields()[1].schema(), other.products);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing CommandCreated instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.avro.CommandCreated other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.commandId)) {
        this.commandId = data().deepCopy(fields()[0].schema(), other.commandId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.products)) {
        this.products = data().deepCopy(fields()[1].schema(), other.products);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'commandId' field.
      * @return The value.
      */
    public long getCommandId() {
      return commandId;
    }


    /**
      * Sets the value of the 'commandId' field.
      * @param value The value of 'commandId'.
      * @return This builder.
      */
    public com.example.avro.CommandCreated.Builder setCommandId(long value) {
      validate(fields()[0], value);
      this.commandId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'commandId' field has been set.
      * @return True if the 'commandId' field has been set, false otherwise.
      */
    public boolean hasCommandId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'commandId' field.
      * @return This builder.
      */
    public com.example.avro.CommandCreated.Builder clearCommandId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'products' field.
      * @return The value.
      */
    public java.util.List<com.example.avro.Product> getProducts() {
      return products;
    }


    /**
      * Sets the value of the 'products' field.
      * @param value The value of 'products'.
      * @return This builder.
      */
    public com.example.avro.CommandCreated.Builder setProducts(java.util.List<com.example.avro.Product> value) {
      validate(fields()[1], value);
      this.products = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'products' field has been set.
      * @return True if the 'products' field has been set, false otherwise.
      */
    public boolean hasProducts() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'products' field.
      * @return This builder.
      */
    public com.example.avro.CommandCreated.Builder clearProducts() {
      products = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CommandCreated build() {
      try {
        CommandCreated record = new CommandCreated();
        record.commandId = fieldSetFlags()[0] ? this.commandId : (java.lang.Long) defaultValue(fields()[0]);
        record.products = fieldSetFlags()[1] ? this.products : (java.util.List<com.example.avro.Product>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CommandCreated>
    WRITER$ = (org.apache.avro.io.DatumWriter<CommandCreated>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CommandCreated>
    READER$ = (org.apache.avro.io.DatumReader<CommandCreated>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.commandId);

    long size0 = this.products.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.example.avro.Product e0: this.products) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.commandId = in.readLong();

      long size0 = in.readArrayStart();
      java.util.List<com.example.avro.Product> a0 = this.products;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.example.avro.Product>((int)size0, SCHEMA$.getField("products").schema());
        this.products = a0;
      } else a0.clear();
      SpecificData.Array<com.example.avro.Product> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.example.avro.Product>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.example.avro.Product e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.example.avro.Product();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.commandId = in.readLong();
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<com.example.avro.Product> a0 = this.products;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.example.avro.Product>((int)size0, SCHEMA$.getField("products").schema());
            this.products = a0;
          } else a0.clear();
          SpecificData.Array<com.example.avro.Product> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.example.avro.Product>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.example.avro.Product e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.example.avro.Product();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










